replicaCount: 2

# Refer to https://docs.livekit.io/deploy/kubernetes/ for instructions

livekit:
  rtc:
    use_external_ip: true
  redis:
    address: redis-master:6379
    # export REDIS_PASSWORD=$(kubectl get secret --namespace redis redis -o jsonpath="{.data.redis-password}" | base64 -d)
    password: ${REDIS_PASSWORD}

  keys:
    APIFZgMqHpxZrfk: esBY2z6aSO2MRimWzl0Ffcm1LIV22r0xN9UXNphc9Bk
  turn:
    enabled: true
    domain: turn1.livekit.cyber.lk
    tls_port: 443
    secretName: turn1-tls-secret

loadBalancer:
  type: do
  # TLS certificate generated automatically with certmanager / letsencrypt
  # secretName is still required. certmanager will place the provisioned
  # certificate in that secret
  clusterIssuer: letsencrypt-prod
  tls:
    - hosts:
        - srv1.livekit.cyber.lk
      secretName: srv1-tls-secret
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 60

# resources are set assuming a 8 core instance
resources:
  limits:
    cpu: 7500m
    memory: 2048Mi
  requests:
    cpu: 7000m
    memory: 1024Mi
